#!/usr/bin/env bash
# =============================================================================
# Hermes Agent — Container Entrypoint
# =============================================================================
# Responsibilities:
#   1. Optionally drop privileges to HERMES_UID:HERMES_GID
#   2. Seed /opt/data/.env  on first run (from host .env or exported vars)
#   3. Seed /opt/data/config.yaml on first run (provider + model)
#   4. Exec the command passed as CMD (default: hermes gateway run)
#
# No API key is required at container start — configure whatever provider
# you need inside .env or via exported environment variables.
# =============================================================================

set -euo pipefail

DATA_DIR="/opt/data"
ENV_FILE="${DATA_DIR}/.env"
CONFIG_FILE="${DATA_DIR}/config.yaml"
FIRST_RUN_MARKER="${DATA_DIR}/.hermes_initialized"

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
HERMES_UID="${HERMES_UID:-10000}"
HERMES_GID="${HERMES_GID:-10000}"
PROVIDER="${PROVIDER:-openai}"
MODEL="${MODEL:-}"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
log()  { echo "[entrypoint] $*"; }
warn() { echo "[entrypoint] ⚠  $*" >&2; }
die()  { echo "[entrypoint] ✗  $*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Ensure the data directory is owned by the hermes user
# ---------------------------------------------------------------------------
chown -R "${HERMES_UID}:${HERMES_GID}" "${DATA_DIR}" 2>/dev/null || true

# ---------------------------------------------------------------------------
# First-run initialisation
# ---------------------------------------------------------------------------
if [[ ! -f "${FIRST_RUN_MARKER}" ]]; then
  log "First run detected — seeding configuration into ${DATA_DIR}"

  # ---- .env ----------------------------------------------------------------
  if [[ ! -f "${ENV_FILE}" ]]; then
    log "Writing ${ENV_FILE}"
    cat > "${ENV_FILE}" <<EOF
# =============================================================================
# Hermes Agent — Runtime secrets
# Generated by entrypoint.sh on first run. Safe to edit manually.
# Docs: https://hermes-agent.nousresearch.com/docs/user-guide/environment-variables
# =============================================================================

# --- Provider selection -----------------------------------------------------
PROVIDER=${PROVIDER}
MODEL=${MODEL}

# --- OpenAI / any OpenAI-compatible endpoint --------------------------------
# Point OPENAI_BASE_URL at a local server, vLLM, LM Studio, etc.
OPENAI_API_KEY=${OPENAI_API_KEY:-}
OPENAI_BASE_URL=${OPENAI_BASE_URL:-}

# --- Anthropic --------------------------------------------------------------
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}

# --- NVIDIA NIM -------------------------------------------------------------
NVIDIA_API_KEY=${NVIDIA_API_KEY:-}

# --- OpenRouter -------------------------------------------------------------
OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}

# --- Google / Gemini --------------------------------------------------------
GOOGLE_API_KEY=${GOOGLE_API_KEY:-}

# --- Ollama (local) ---------------------------------------------------------
OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-}

# --- LM Studio (local) ------------------------------------------------------
LM_BASE_URL=${LM_BASE_URL:-}

# --- DeepSeek ---------------------------------------------------------------
DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}

# --- xAI / Grok -------------------------------------------------------------
XAI_API_KEY=${XAI_API_KEY:-}

# --- Mistral ----------------------------------------------------------------
MISTRAL_API_KEY=${MISTRAL_API_KEY:-}

# --- HuggingFace ------------------------------------------------------------
HF_TOKEN=${HF_TOKEN:-}

# --- Tool APIs (optional) ---------------------------------------------------
TAVILY_API_KEY=${TAVILY_API_KEY:-}
FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY:-}
EXA_API_KEY=${EXA_API_KEY:-}
EOF
    chown "${HERMES_UID}:${HERMES_GID}" "${ENV_FILE}"
    chmod 600 "${ENV_FILE}"
    log ".env written (mode 600)"
  else
    log ".env already exists — skipping write"
  fi

  # ---- config.yaml ---------------------------------------------------------
  if [[ ! -f "${CONFIG_FILE}" ]]; then
    log "Writing ${CONFIG_FILE}"

    # Build provider block dynamically based on PROVIDER
    case "${PROVIDER}" in
      openai|custom)
        BASE_URL="${OPENAI_BASE_URL:-https://api.openai.com/v1}"
        KEY_ENV="OPENAI_API_KEY"
        DEFAULT_MODEL="${MODEL:-gpt-4o}"
        ;;
      anthropic)
        BASE_URL="${ANTHROPIC_BASE_URL:-https://api.anthropic.com}"
        KEY_ENV="ANTHROPIC_API_KEY"
        DEFAULT_MODEL="${MODEL:-claude-sonnet-4-20250514}"
        ;;
      nvidia)
        BASE_URL="${NVIDIA_BASE_URL:-https://integrate.api.nvidia.com/v1}"
        KEY_ENV="NVIDIA_API_KEY"
        DEFAULT_MODEL="${MODEL:-meta/llama-3.1-70b-instruct}"
        ;;
      openrouter)
        BASE_URL="${OPENROUTER_BASE_URL:-https://openrouter.ai/api/v1}"
        KEY_ENV="OPENROUTER_API_KEY"
        DEFAULT_MODEL="${MODEL:-meta-llama/llama-3.1-70b-instruct}"
        ;;
      gemini|google)
        BASE_URL="${GEMINI_BASE_URL:-}"
        KEY_ENV="GOOGLE_API_KEY"
        DEFAULT_MODEL="${MODEL:-gemini-2.0-flash}"
        ;;
      ollama)
        BASE_URL="${OLLAMA_BASE_URL:-http://host.docker.internal:11434}"
        KEY_ENV="OLLAMA_API_KEY"
        DEFAULT_MODEL="${MODEL:-llama3.1}"
        ;;
      lmstudio)
        BASE_URL="${LM_BASE_URL:-http://host.docker.internal:1234/v1}"
        KEY_ENV="LM_API_KEY"
        DEFAULT_MODEL="${MODEL:-local-model}"
        ;;
      deepseek)
        BASE_URL="${DEEPSEEK_BASE_URL:-https://api.deepseek.com/v1}"
        KEY_ENV="DEEPSEEK_API_KEY"
        DEFAULT_MODEL="${MODEL:-deepseek-chat}"
        ;;
      xai)
        BASE_URL="${XAI_BASE_URL:-https://api.x.ai/v1}"
        KEY_ENV="XAI_API_KEY"
        DEFAULT_MODEL="${MODEL:-grok-2}"
        ;;
      mistral)
        BASE_URL="${MISTRAL_BASE_URL:-https://api.mistral.ai/v1}"
        KEY_ENV="MISTRAL_API_KEY"
        DEFAULT_MODEL="${MODEL:-mistral-large-latest}"
        ;;
      *)
        warn "Unknown provider '${PROVIDER}' — writing a generic openai-compatible block."
        BASE_URL="${OPENAI_BASE_URL:-}"
        KEY_ENV="OPENAI_API_KEY"
        DEFAULT_MODEL="${MODEL:-}"
        ;;
    esac

    cat > "${CONFIG_FILE}" <<EOF
# =============================================================================
# Hermes Agent — Configuration
# Generated by entrypoint.sh on first run. Safe to edit manually.
# Docs: https://hermes-agent.nousresearch.com/docs/user-guide/configuration
# =============================================================================

model:
  provider: ${PROVIDER}
  default: "${DEFAULT_MODEL}"

providers:
  ${PROVIDER}:
    base_url: "${BASE_URL}"
    key_env: ${KEY_ENV}
    type: openai
    timeout_seconds: 300

terminal:
  backend: local
EOF
    chown "${HERMES_UID}:${HERMES_GID}" "${CONFIG_FILE}"
    log "config.yaml written (provider: ${PROVIDER}, model: ${DEFAULT_MODEL})"
  else
    log "config.yaml already exists — skipping write"
  fi

  touch "${FIRST_RUN_MARKER}"
  chown "${HERMES_UID}:${HERMES_GID}" "${FIRST_RUN_MARKER}"
  log "Initialisation complete ✓"

else
  log "Data directory already initialised — skipping first-run setup"
fi

# ---------------------------------------------------------------------------
# Drop privileges and exec
# ---------------------------------------------------------------------------
log "Starting as UID=${HERMES_UID} GID=${HERMES_GID} — provider: ${PROVIDER}"

export HOME="/home/hermes"

exec gosu "${HERMES_UID}:${HERMES_GID}" /usr/local/bin/hermes "$@"
