#!/usr/bin/env bash
# =============================================================================
# Hermes Agent — Container Entrypoint
# =============================================================================
# Responsibilities:
#   1. Optionally drop privileges to HERMES_UID:HERMES_GID
#   2. Seed /opt/data/.env  on first run (writes NVIDIA API key + any extras)
#   3. Seed /opt/data/config.yaml on first run (NVIDIA provider + chosen model)
#   4. Exec the command passed as CMD (default: gateway run)
#
# Environment variables consumed (all set via .env / docker-compose.yml):
#   NVIDIA_API_KEY      — required; your nvapi-... key from build.nvidia.com
#   NVIDIA_MODEL        — model ref, default: meta/llama-3.1-70b-instruct
#   HERMES_UID          — UID to run as inside the container   (default: 10000)
#   HERMES_GID          — GID to run as inside the container   (default: 10000)
#   HERMES_DASHBOARD    — set to 1 to enable the web dashboard (default: 0)
#   HERMES_DASHBOARD_INSECURE — set to 1 to skip OAuth gate on dashboard
#   API_SERVER_ENABLED  — set to true to expose the OpenAI-compat API server
#   API_SERVER_HOST     — bind address for the API server (default: 0.0.0.0)
#   API_SERVER_KEY      — auth key for the API server (min 8 chars)
# =============================================================================

set -euo pipefail

DATA_DIR="/opt/data"
ENV_FILE="${DATA_DIR}/.env"
CONFIG_FILE="${DATA_DIR}/config.yaml"
FIRST_RUN_MARKER="${DATA_DIR}/.hermes_initialized"

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
HERMES_UID="${HERMES_UID:-10000}"
HERMES_GID="${HERMES_GID:-10000}"
NVIDIA_MODEL="${NVIDIA_MODEL:-meta/llama-3.1-70b-instruct}"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
log()  { echo "[entrypoint] $*"; }
warn() { echo "[entrypoint] ⚠  $*" >&2; }
die()  { echo "[entrypoint] ✗  $*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Validate required variables
# ---------------------------------------------------------------------------
if [[ -z "${NVIDIA_API_KEY:-}" ]]; then
  die "NVIDIA_API_KEY is not set. Add it to your .env file and restart.
  Get a free key at: https://build.nvidia.com/settings/api-keys"
fi

# ---------------------------------------------------------------------------
# Ensure the data directory is owned by the hermes user.
# This handles the case where docker creates the volume as root.
# ---------------------------------------------------------------------------
chown -R "${HERMES_UID}:${HERMES_GID}" "${DATA_DIR}" 2>/dev/null || true

# ---------------------------------------------------------------------------
# First-run initialisation
# ---------------------------------------------------------------------------
if [[ ! -f "${FIRST_RUN_MARKER}" ]]; then
  log "First run detected — seeding configuration into ${DATA_DIR}"

  # ---- .env ----------------------------------------------------------------
  # Only write if it doesn't already exist (user may have placed their own).
  if [[ ! -f "${ENV_FILE}" ]]; then
    log "Writing ${ENV_FILE}"
    cat > "${ENV_FILE}" <<EOF
# =============================================================================
# Hermes Agent — Runtime secrets
# Generated by entrypoint.sh on first run. Safe to edit manually.
# =============================================================================

# NVIDIA NIM (https://build.nvidia.com)
NVIDIA_API_KEY=${NVIDIA_API_KEY}

# Add any other provider keys below, e.g.:
# OPENROUTER_API_KEY=
# ANTHROPIC_API_KEY=
# TELEGRAM_BOT_TOKEN=
EOF
    chown "${HERMES_UID}:${HERMES_GID}" "${ENV_FILE}"
    chmod 600 "${ENV_FILE}"
    log ".env written (mode 600)"
  else
    log ".env already exists — skipping write"
    # Still inject/update the NVIDIA key in case it changed in the host .env
    if grep -q "^NVIDIA_API_KEY=" "${ENV_FILE}"; then
      sed -i "s|^NVIDIA_API_KEY=.*|NVIDIA_API_KEY=${NVIDIA_API_KEY}|" "${ENV_FILE}"
    else
      echo "NVIDIA_API_KEY=${NVIDIA_API_KEY}" >> "${ENV_FILE}"
    fi
  fi

  # ---- config.yaml ---------------------------------------------------------
  if [[ ! -f "${CONFIG_FILE}" ]]; then
    log "Writing ${CONFIG_FILE}"
    cat > "${CONFIG_FILE}" <<EOF
# =============================================================================
# Hermes Agent — Configuration
# Generated by entrypoint.sh on first run. Safe to edit manually.
# Docs: https://hermes-agent.nousresearch.com/docs/user-guide/configuration
# =============================================================================

# ---------------------------------------------------------------------------
# Primary model — NVIDIA NIM (OpenAI-compatible, free tier)
# Change NVIDIA_MODEL in your .env to switch models without editing this file.
# Full model list: https://build.nvidia.com/models
# ---------------------------------------------------------------------------
model:
  provider: nvidia
  default: "${NVIDIA_MODEL}"

# ---------------------------------------------------------------------------
# Named provider block for NVIDIA NIM.
# api_key is read from the NVIDIA_API_KEY env var (written to .env above).
# ---------------------------------------------------------------------------
providers:
  nvidia:
    base_url: "https://integrate.api.nvidia.com/v1"
    key_env: NVIDIA_API_KEY
    type: openai
    timeout_seconds: 300

# ---------------------------------------------------------------------------
# Terminal backend — local by default (safest inside a container).
# Switch to "docker" if you want the agent to execute commands in an
# isolated sandbox container (requires Docker-in-Docker or socket mount).
# ---------------------------------------------------------------------------
terminal:
  backend: local
EOF
    chown "${HERMES_UID}:${HERMES_GID}" "${CONFIG_FILE}"
    log "config.yaml written"
  else
    log "config.yaml already exists — skipping write"
  fi

  # Mark initialisation complete so we skip this block on subsequent starts.
  touch "${FIRST_RUN_MARKER}"
  chown "${HERMES_UID}:${HERMES_GID}" "${FIRST_RUN_MARKER}"
  log "Initialisation complete ✓"
else
  log "Data directory already initialised — skipping first-run setup"
  # Always keep the API key in sync with whatever is in the host .env
  if [[ -f "${ENV_FILE}" ]]; then
    if grep -q "^NVIDIA_API_KEY=" "${ENV_FILE}"; then
      sed -i "s|^NVIDIA_API_KEY=.*|NVIDIA_API_KEY=${NVIDIA_API_KEY}|" "${ENV_FILE}"
    else
      echo "NVIDIA_API_KEY=${NVIDIA_API_KEY}" >> "${ENV_FILE}"
    fi
  fi
fi

# ---------------------------------------------------------------------------
# Drop privileges and exec the requested command
# ---------------------------------------------------------------------------
log "Starting as UID=${HERMES_UID} GID=${HERMES_GID}: hermes $*"

export HOME="/home/hermes"

exec gosu "${HERMES_UID}:${HERMES_GID}" /usr/local/bin/hermes "$@"
